### ISSUE TITLE
请求添加多线程或异步

### ISSUE THREAD

**Issue by mwxsrmw** [Sn0wo2/Crasher#24]
我的服务端在cancel_packets恢复的时候会卡顿0.1秒

**Comment by Sn0wo2** [comment]
这是来自QQ邮箱的假期自动回复邮件。你好，我最近正在休假中，无法亲自回复你的邮件。我将在假期结束后，尽快给你回复。

**Comment by Sn0wo2** [comment]
计划在下个版本添加，感谢你的反馈

**Comment by Sn0wo2** [comment]
经实测异步不是很好处理，异步下次一定，但我们计划优化代码，几乎不会出现此问题

**Comment by Sn0wo2** [comment]
请查看最新更新：https://github.com/Sn0wo2/Crasher/releases
